<?php 
return array (
  'site_name' => '微信多用户微信营销系统',
  'site_title' => '微信公众平台源码,微信机器人源码,微信自动回复源码',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://pigcms.com',
  'site_my' => '小猪猪',
  'server_key' => '2315af258614bdf40697ebbdfa',
  'server_topdomain' => 'pigcms.com',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'reg_groupid' => '4',
  'reg_validdays' => '30',
  'router_key' => '',
  'ipc' => '粤ICP备11104265号',
  'site_qq' => '123456',
  'site_mp' => '',
  'baidu_map_api' => 'pDux46lHyuAMjL3fiv7rGBry',
  'site_email' => 'admin@pigcms.com',
  'keyword' => '关键词小猪猪',
  'content' => '描述',
  'countsz' => '',
  'copyright' => 'Copyright © 2012-2013 pigcms 版权所有',
);