<?php
$templates=array(
array('name'=>'模板1','templateindex'=>'zongse','intro'=>''),
array('name'=>'模板2','templateindex'=>'tianlan','intro'=>''),
array('name'=>'模板3','templateindex'=>'danhui','intro'=>''),
array('name'=>'餐饮类1','templateindex'=>'hongsecanting','intro'=>''),
array('name'=>'模板4','templateindex'=>'lvsecanyin','intro'=>''),
array('name'=>'模板5','templateindex'=>'blue1','intro'=>''),
array('name'=>'模板6','templateindex'=>'gangse','intro'=>''),
array('name'=>'模板7','templateindex'=>'red1','intro'=>''),
array('name'=>'模板8','templateindex'=>'v10','intro'=>''),
array('name'=>'模板9','templateindex'=>'v12','intro'=>''),
array('name'=>'模板10','templateindex'=>'ertonglipin','intro'=>''),
array('name'=>'模板11','templateindex'=>'v14','intro'=>''),
array('name'=>'模板12','templateindex'=>'v15','intro'=>''),
array('name'=>'模板13','templateindex'=>'v16','intro'=>''),
array('name'=>'模板14','templateindex'=>'v17','intro'=>''),
array('name'=>'模板15','templateindex'=>'v19','intro'=>''),
)
?>